#!/usr/bin/env bash
set -e

HERE="$(dirname "$(readlink -f "$0")")"
APP_BASE="$HERE/usr/lib/jgex"

export JAVA_HOME="$APP_BASE/jdk"
export PATH="$JAVA_HOME/bin:$PATH"

# needed for help
cd "$APP_BASE/bin"

exec "$APP_BASE/bin/Java-Geometry-Expert" "$@"
